[enb]
enb_id = 0x19B
mcc = 901
mnc = 70

mme_addr = 127.0.0.2

gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1

n_prb = 50

[enb_files]
sib_config = sib.conf
rr_config = rr.conf
rb_config = rb.conf

[rf]
device_name = zmq

device_args = fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://127.0.0.1:2001,id=enb,base_srate=23.04e6

[log]
all_level = info
phy_level = info
mac_level = info
rlc_level = info
pdcp_level = info
rrc_level = debug
s1ap_level = debug

[pcap]
enable = true
filename = /tmp/lte-lab/enb.pcap
