[enb]
enb_id = 0x19B
enb_name = LTE-LAB

[enb_files]
sib_config = sib.conf
rr_config = rr.conf
rb_config = rb.conf

[rf]
dl_earfcn = 3400
tx_gain = 0
rx_gain = 0

device_name = zmq

device_args = tx_port=tcp://*:2000,rx_port=tcp://127.0.0.1:2001,id=enb,base_srate=23.04e6

[expert]
tx_time_offset = auto

[gui]
enable = false

[log]
all_level = info
phy_level = info
mac_level = info
rlc_level = info
pdcp_level = info
rrc_level = info
nas_level = info

[pcap]
enable = true
filename = /tmp/lte-lab/enb.pcap
