[mme]
mme_code = 0x1
mme_group = 0x1

[mme]
apn = internet

[spgw]
gtpu_bind_addr = 127.0.1.1
sgi_if_addr = 10.45.0.1

[hss]
db_file = /tmp/lte-lab/user_db.csv

[log]
all_level = info
nas_level = debug
gtpc_level = debug
