[rf]
device_name = zmq

device_args = tx_port=tcp://*:2001,rx_port=tcp://127.0.0.1:2000,id=ue,base_srate=23.04e6

[rat.eutra]
dl_earfcn = 3400

[usim]
mode = soft

algo = milenage

opc = 63BFA50EE6523365FF14C1F45F88737D

k = 00112233445566778899AABBCCDDEEFF

imsi = 001010123456789

imei = 356938035643809

[rrc]
release = 8

[nas]
apn = internet

[log]
all_level = info
phy_level = info
mac_level = info
rlc_level = info
pdcp_level = info
rrc_level = info
nas_level = debug

[pcap]
enable = true
filename = /tmp/lte-lab/ue_nas.pcap
